### ISSUE TITLE
[not an issue] Use notroot to install apt!

### ISSUE THREAD

**Issue by ayunami2000** [Gregwar/notroot#3]
![image](https://user-images.githubusercontent.com/24785136/73269087-2a692100-41aa-11ea-9725-8b026677c6f9.png)

**Comment by ayunami2000** [comment]
wait im big dumb nvm

please ignore

**Comment by Gregwar** [comment]
What were you trying to achieve ? :smiley:

**Comment by ayunami2000** [comment]
I was trying to use apt repositories with notroot
